# Generated by Django 5.0.4 on 2024-04-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_remove_task_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
