# Generated by Django 5.0.4 on 2024-04-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0006_task_iscompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='content',
            new_name='change',
        ),
        migrations.RemoveField(
            model_name='task',
            name='iscompleted',
        ),
    ]
