# Generated by Django 5.0.4 on 2024-04-21 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0007_rename_content_task_change_remove_task_iscompleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='change',
            new_name='content',
        ),
        migrations.AddField(
            model_name='task',
            name='iscompleted',
            field=models.BooleanField(default=False),
        ),
    ]
